import { Router, Request, Response } from 'express';
import prisma from '../db/prisma';
import { DEMO_USER_ID } from '../constants';

const router = Router();

/**
 * POST /api/actions/execute
 * Executes a proposed counter-action generated by the Multi-Agent Council
 */
router.post('/execute', async (req: Request, res: Response) => {
  try {
    const { insightId, actionId, actionType, payload } = req.body;
    const userId = req.body.userId || DEMO_USER_ID;

    if (!insightId || !actionId) {
      return res.status(400).json({ success: false, error: 'insightId and actionId are required' });
    }

    const insight = await prisma.insight.findUnique({ where: { id: insightId } });
    if (!insight || insight.userId !== userId) {
      return res.status(404).json({ success: false, error: 'Insight not found' });
    }

    // Update action status in the insight JSON
    const actions = (insight.actions as any[]) || [];
    const requestedAction = actions.find(act => act.id === actionId);
    if (!requestedAction) {
      return res.status(404).json({ success: false, error: 'Action not found for insight' });
    }
    if (requestedAction.status !== 'pending') {
      return res.status(409).json({ success: false, error: 'Action is no longer pending' });
    }

    const updatedActions = actions.map(act => {
      if (act.id === actionId) {
        return { ...act, status: 'executed', executedAt: new Date().toISOString() };
      }
      return act;
    });

    await prisma.insight.update({
      where: { id: insightId },
      data: { actions: updatedActions },
    });

    const requestedActionType = requestedAction.actionType || actionType;
    let executionMessage = 'Recommendation acknowledged successfully.';
    if (requestedActionType === 'invoice_nudge') {
      executionMessage = 'Invoice reminder recommendation acknowledged for user review.';
    } else if (requestedActionType === 'sip_pause') {
      executionMessage = 'SIP pause recommendation acknowledged for user review.';
    } else if (requestedActionType === 'budget_shift') {
      executionMessage = 'Discretionary spending recommendation acknowledged for user review.';
    }

    console.log(`⚡ [ACTION EXECUTED] ${actionType} (${actionId}) on Insight ${insightId.substring(0, 8)}`);

    res.json({
      success: true,
      message: executionMessage,
      actionId,
      actionType: requestedActionType,
      status: 'executed',
      timestamp: new Date().toISOString(),
    });
  } catch (error: any) {
    console.error('Error executing counter-action:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

export default router;
