import { Router, Request, Response } from 'express';
import prisma from '../db/prisma';
import { DEMO_USER_ID } from '../constants';

const router = Router();

/**
 * POST /api/actions/execute
 * Executes a proposed counter-action generated by the Multi-Agent Council
 */
router.post('/execute', async (req: Request, res: Response) => {
  try {
    const { insightId, actionId, actionType, payload } = req.body;
    const userId = req.body.userId || DEMO_USER_ID;

    if (!insightId || !actionId) {
      return res.status(400).json({ success: false, error: 'insightId and actionId are required' });
    }

    const insight = await prisma.insight.findUnique({ where: { id: insightId } });
    if (!insight) {
      return res.status(404).json({ success: false, error: 'Insight not found' });
    }

    // Update action status in the insight JSON
    const actions = (insight.actions as any[]) || [];
    const updatedActions = actions.map(act => {
      if (act.id === actionId) {
        return { ...act, status: 'executed', executedAt: new Date().toISOString() };
      }
      return act;
    });

    await prisma.insight.update({
      where: { id: insightId },
      data: { actions: updatedActions },
    });

    let executionMessage = 'Action executed successfully.';
    if (actionType === 'invoice_nudge') {
      executionMessage = `📧 Invoice payment reminder successfully dispatched to ${payload?.recipient || 'client'}!`;
    } else if (actionType === 'sip_pause') {
      executionMessage = '⏸️ Mutual Fund SIP pause requested for the upcoming cycle to protect buffer.';
    } else if (actionType === 'budget_shift') {
      executionMessage = '🛡️ Temporary 7-day spending soft-cap activated on discretionary categories.';
    }

    console.log(`⚡ [ACTION EXECUTED] ${actionType} (${actionId}) on Insight ${insightId.substring(0, 8)}`);

    res.json({
      success: true,
      message: executionMessage,
      actionId,
      actionType,
      status: 'executed',
      timestamp: new Date().toISOString(),
    });
  } catch (error: any) {
    console.error('Error executing counter-action:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

export default router;
