import 'package:flutter/material.dart';
import '../models/insight.dart';
import 'graph_path_view.dart';

class InsightCard extends StatefulWidget {
  final Insight insight;
  final bool isSuppressed;

  const InsightCard({
    super.key,
    required this.insight,
    this.isSuppressed = false,
  });

  @override
  State<InsightCard> createState() => _InsightCardState();
}

class _InsightCardState extends State<InsightCard> {
  bool _isExpanded = false;

  @override
  Widget build(BuildContext context) {
    final ins = widget.insight;
    final isCascade = ins.triggerType == 'cascade';
    final themeColor = isCascade ? const Color(0xFFFF5252) : const Color(0xFF64B5F6);

    return Card(
      margin: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
      elevation: 2,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: BorderSide(
          color: widget.isSuppressed
              ? Colors.white10
              : themeColor.withOpacity(0.4),
          width: widget.isSuppressed ? 1 : 1.5,
        ),
      ),
      color: const Color(0xFF161A26),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header Row: Trigger Badge & Gate Score Pill
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                      decoration: BoxDecoration(
                        color: themeColor.withOpacity(0.15),
                        borderRadius: BorderRadius.circular(20),
                        border: Border.all(color: themeColor.withOpacity(0.6)),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(
                            isCascade ? Icons.warning_amber_rounded : Icons.trending_up_rounded,
                            color: themeColor,
                            size: 14,
                          ),
                          const SizedBox(width: 4),
                          Text(
                            isCascade ? 'CASCADE RISK' : 'BEHAVIORAL ANOMALY',
                            style: TextStyle(
                              color: themeColor,
                              fontSize: 11,
                              fontWeight: FontWeight.bold,
                              letterSpacing: 0.5,
                            ),
                          ),
                        ],
                      ),
                    ),
                    if (widget.isSuppressed) ...[
                      const SizedBox(width: 6),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                        decoration: BoxDecoration(
                          color: Colors.white10,
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: const Text(
                          'SUPPRESSED',
                          style: TextStyle(color: Colors.white54, fontSize: 10, fontWeight: FontWeight.bold),
                        ),
                      ),
                    ],
                  ],
                ),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: const Color(0xFF222838),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    children: [
                      const Text(
                        'Gate Score: ',
                        style: TextStyle(color: Colors.white54, fontSize: 11),
                      ),
                      Text(
                        ins.gateScore.toStringAsFixed(1),
                        style: TextStyle(
                          color: widget.isSuppressed ? Colors.white54 : Colors.greenAccent,
                          fontWeight: FontWeight.bold,
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),

            // Plain Language Narrative generated by Reasoning Agent
            Text(
              ins.explanation,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 14,
                height: 1.45,
                fontWeight: FontWeight.w400,
              ),
            ),
            const SizedBox(height: 14),

            // Score Metrics Mini Bar
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: BoxDecoration(
                color: const Color(0xFF0F131C),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  _buildMetric('Severity', '${ins.severity.toInt()}%', themeColor),
                  Container(height: 16, width: 1, color: Colors.white12),
                  _buildMetric('Confidence', '${ins.confidence.toInt()}%', Colors.amberAccent),
                  Container(height: 16, width: 1, color: Colors.white12),
                  _buildMetric('Urgency', '${ins.urgency.toInt()}%', Colors.orangeAccent),
                ],
              ),
            ),
            const SizedBox(height: 10),

            // Expandable "Why?" Button
            if (ins.graphPath != null) ...[
              InkWell(
                onTap: () => setState(() => _isExpanded = !_isExpanded),
                borderRadius: BorderRadius.circular(8),
                child: Padding(
                  padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 4),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Row(
                        children: [
                          Icon(
                            _isExpanded ? Icons.expand_less : Icons.expand_more,
                            color: Colors.amberAccent,
                            size: 18,
                          ),
                          const SizedBox(width: 6),
                          const Text(
                            'Why? (Inspect Causal Graph Path)',
                            style: TextStyle(
                              color: Colors.amberAccent,
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ],
                      ),
                      Text(
                        _isExpanded ? 'Hide' : 'Inspect',
                        style: const TextStyle(color: Colors.white38, fontSize: 11),
                      ),
                    ],
                  ),
                ),
              ),
              if (_isExpanded) ...[
                const SizedBox(height: 8),
                GraphPathView(
                  graphPath: ins.graphPath!,
                  triggerType: ins.triggerType,
                ),
              ],
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildMetric(String label, String value, Color color) {
    return Row(
      children: [
        Text(
          '$label: ',
          style: const TextStyle(color: Colors.white54, fontSize: 11),
        ),
        Text(
          value,
          style: TextStyle(color: color, fontSize: 12, fontWeight: FontWeight.bold),
        ),
      ],
    );
  }
}
